/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GearRouteImport } from './routes/gear'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as ApiPhotosRouteImport } from './routes/api/photos'
import { Route as PhotosOtherRouteImport } from './routes/photos_.other'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'
import { Route as PhotosTripsTripIdRouteImport } from './routes/photos_.trips.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GearRoute = GearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotosRoute = ApiPhotosRouteImport.update({
  id: '/api/photos',
  path: '/api/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosOtherRoute = PhotosOtherRouteImport.update({
  id: '/photos_/other',
  path: '/photos/other',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosTripsTripIdRoute = PhotosTripsTripIdRouteImport.update({
  id: '/photos_/trips/$tripId',
  path: '/photos/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gear': typeof GearRoute
  '/photos': typeof PhotosRoute
  '/api/photos': typeof ApiPhotosRoute
  '/photos/other': typeof PhotosOtherRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/photos/trips/$tripId': typeof PhotosTripsTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gear': typeof GearRoute
  '/photos': typeof PhotosRoute
  '/api/photos': typeof ApiPhotosRoute
  '/photos/other': typeof PhotosOtherRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/writing': typeof WritingIndexRoute
  '/photos/trips/$tripId': typeof PhotosTripsTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gear': typeof GearRoute
  '/photos': typeof PhotosRoute
  '/api/photos': typeof ApiPhotosRoute
  '/photos_/other': typeof PhotosOtherRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/photos_/trips/$tripId': typeof PhotosTripsTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gear'
    | '/photos'
    | '/api/photos'
    | '/photos/other'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/projects/'
    | '/writing/'
    | '/photos/trips/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gear'
    | '/photos'
    | '/api/photos'
    | '/photos/other'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/projects'
    | '/writing'
    | '/photos/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/gear'
    | '/photos'
    | '/api/photos'
    | '/photos_/other'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/projects/'
    | '/writing/'
    | '/photos_/trips/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GearRoute: typeof GearRoute
  PhotosRoute: typeof PhotosRoute
  ApiPhotosRoute: typeof ApiPhotosRoute
  PhotosOtherRoute: typeof PhotosOtherRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  WritingSlugRoute: typeof WritingSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  WritingIndexRoute: typeof WritingIndexRoute
  PhotosTripsTripIdRoute: typeof PhotosTripsTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear': {
      id: '/gear'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photos': {
      id: '/api/photos'
      path: '/api/photos'
      fullPath: '/api/photos'
      preLoaderRoute: typeof ApiPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos_/other': {
      id: '/photos_/other'
      path: '/photos/other'
      fullPath: '/photos/other'
      preLoaderRoute: typeof PhotosOtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos_/trips/$tripId': {
      id: '/photos_/trips/$tripId'
      path: '/photos/trips/$tripId'
      fullPath: '/photos/trips/$tripId'
      preLoaderRoute: typeof PhotosTripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GearRoute: GearRoute,
  PhotosRoute: PhotosRoute,
  ApiPhotosRoute: ApiPhotosRoute,
  PhotosOtherRoute: PhotosOtherRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  WritingSlugRoute: WritingSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  WritingIndexRoute: WritingIndexRoute,
  PhotosTripsTripIdRoute: PhotosTripsTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
